[package]
name = "test_cuda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.1.7"
chrono = "0.4.38"
cudarc = { version = "0.11.8", features = ["cuda-11080"] }
